"""
Feature schema for the heart disease dataset used in this project.

IMPORTANT — documented vs. observed encoding
---------------------------------------------
The UCI "Heart Disease" repository page (archive.ics.uci.edu/dataset/45)
documents the original Cleveland attribute encoding as:
    cp      : 1=typical angina, 2=atypical angina, 3=non-anginal, 4=asymptomatic
    restecg : 0=normal, 1=ST-T abnormality, 2=probable/definite LVH
    slope   : 1=upsloping, 2=flat, 3=downsloping
    thal    : 3=normal, 6=fixed defect, 7=reversible defect
    num     : 0=absence, 1-4=increasing presence (multi-class)

The CSV ingested in this project (see docs/DATA_DICTIONARY.md for full
provenance) uses a widely-circulated, zero-indexed, already-binarized
recoding of the same 303 Cleveland patients:
    cp      : 0-3 instead of 1-4
    slope   : 0-2 instead of 1-3
    thal    : 0-3 instead of {3,6,7}
    target  : already binarized to {0,1} instead of raw {0,1,2,3,4}

Both encodings are legitimate and this discrepancy is intentionally
documented rather than silently assumed — see the "Encoding Discrepancy"
finding in docs/DATA_DICTIONARY.md and the validation report generated by
`training/src/data/validation.py`.
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class FeatureRange:
    dtype: str
    min_value: float
    max_value: float
    description: str


# Clinical plausibility ranges used for range validation (BR-002 / TR-002).
# Bounds are deliberately generous (physiological plausibility, not the
# narrow observed range in this 303-row sample) so validation catches
# genuinely bad values without rejecting legitimate edge-case patients.
FEATURE_SCHEMA: dict[str, FeatureRange] = {
    "age": FeatureRange("int", 0, 120, "Age in years"),
    "sex": FeatureRange("int", 0, 1, "1 = male, 0 = female"),
    "cp": FeatureRange("int", 0, 3, "Chest pain type (0-3, dataset-observed encoding)"),
    "trestbps": FeatureRange("int", 60, 260, "Resting blood pressure (mm Hg)"),
    "chol": FeatureRange("int", 50, 700, "Serum cholesterol (mg/dl)"),
    "fbs": FeatureRange("int", 0, 1, "Fasting blood sugar > 120 mg/dl (1=true)"),
    "restecg": FeatureRange("int", 0, 2, "Resting ECG result (0-2)"),
    "thalach": FeatureRange("int", 60, 250, "Max heart rate achieved"),
    "exang": FeatureRange("int", 0, 1, "Exercise-induced angina (1=yes)"),
    "oldpeak": FeatureRange("float", 0.0, 7.0, "ST depression induced by exercise"),
    "slope": FeatureRange("int", 0, 2, "Slope of peak exercise ST segment (0-2)"),
    "ca": FeatureRange("int", 0, 3, "Number of major vessels colored by fluoroscopy (0-3 documented)"),
    "thal": FeatureRange("int", 1, 3, "Thalassemia code (1-3 documented in this recoding)"),
    "target": FeatureRange("int", 0, 1, "1 = heart disease present, 0 = absent"),
}

FEATURE_COLUMNS = [c for c in FEATURE_SCHEMA if c != "target"]
TARGET_COLUMN = "target"
ALL_COLUMNS = list(FEATURE_SCHEMA.keys())
